from __future__ import annotations

import discord
from discord import app_commands


RU_COMMAND_NAMES: dict[str, str] = {
    "add": "добавить",
    "afisha": "афиша",
    "ai": "ии",
    "ai_config": "ии_настройки",
    "ai_relation": "ии_отношения",
    "ask": "спросить",
    "autoplay": "автоплей",
    "ban": "бан",
    "bot_settings": "настройки",
    "channel_disable": "канал_выкл",
    "channel_enable": "канал_вкл",
    "clear": "очистить",
    "clearwarns": "снять_варны",
    "close": "закрыть",
    "club": "клуб",
    "config": "настройки",
    "create": "создать",
    "creepy": "крипота",
    "current": "трек",
    "delete": "удалить",
    "divorce": "развод",
    "forget_me": "забыть_меня",
    "genres": "жанры",
    "helpme": "помогите",
    "history": "история",
    "how": "как",
    "image_describe": "описать_картинку",
    "kick": "кик",
    "leave": "выйти",
    "list": "список",
    "marry": "предложить",
    "memory_clear_channel": "очистить_канал",
    "memory_clear_user": "очистить_пользователя",
    "messages": "сообщения",
    "mood_set": "настроение",
    "movie": "фильм",
    "movies": "фильмы",
    "music": "музыка",
    "mute": "мут",
    "next": "следующим",
    "now": "сейчас",
    "nowplaying": "сейчас",
    "off": "выкл",
    "panel": "пульт",
    "pairs": "пары",
    "pet": "питомец",
    "pause": "пауза",
    "play": "включить",
    "privacy": "приватность",
    "private": "лично",
    "profile": "профиль",
    "profile_user": "профиль_участника",
    "post": "опубликовать",
    "queue": "очередь",
    "rating": "оценка",
    "random_replies": "случайные_ответы",
    "rank": "ранг",
    "reaction_ban": "запрет_реакций",
    "reaction_ban_list": "список_запретов",
    "reaction_unban": "разрешить_реакции",
    "reactionroles": "роли_реакций",
    "reactions": "реакции",
    "relations": "отношения",
    "relationships": "отношения",
    "remove": "убрать",
    "reset": "сброс",
    "resume": "продолжить",
    "results": "итоги",
    "rules": "правила",
    "rules_minecraft": "правила_майнкрафт",
    "role": "роль",
    "say": "сказать",
    "say_embed": "сказать_эмбед",
    "set": "настроить",
    "set_log_channel": "лог_канал",
    "set_matchmaking": "знакомства",
    "set_profile_analytics": "аналитика_профилей",
    "set_story_nsfw": "нсфв_история",
    "shop_panel": "магазин",
    "show": "показать",
    "shuffle": "перемешать",
    "skip": "пропустить",
    "stats": "статистика",
    "status": "статус",
    "stop": "стоп",
    "story": "история",
    "support_panel": "поддержка",
    "top": "топ",
    "unban": "разбан",
    "unmute": "размут",
    "volume": "громкость",
    "warn": "варн",
    "warnings": "варны",
    "wedding": "свадьба",
    "welcome": "приветствие",
}


class RussianCommandNameTranslator(app_commands.Translator):
    async def translate(
        self,
        string: app_commands.locale_str,
        locale: discord.Locale,
        context: app_commands.TranslationContextTypes,
    ) -> str | None:
        if locale is not discord.Locale.russian:
            return None
        if context.location not in {
            app_commands.TranslationContextLocation.command_name,
            app_commands.TranslationContextLocation.group_name,
        }:
            return None
        return RU_COMMAND_NAMES.get(string.message)
